<?php
include_once "Product.php";
$block = new Product();
var_dump($block->getData());
?>


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>project</title>
</head>
<body>


<!---->
<!--<div class ="product-list">-->
<!--    --><?php //foreach ($block->getData() as $products): ?>
<!--    --><?php //var_dump($products); ?>
<!--    --><?php //endforeach; ?>
<!--</div>-->
<div></div>
<?php foreach ($block->getData() as $products): ?>
<h1>
    <?= $products['img']; ?>
    <?= $products['title']; ?>
    <?= $products['rating']; ?>
</h1>
<?php endforeach; ?>
</body>
</html>